# Generated by Django 5.0.2 on 2024-03-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment',
            field=models.TextField(default='lorem ipsum lorem ipsum lorem ipsum '),
            preserve_default=False,
        ),
    ]
